export * from './default-entity.interface';
export * from './amenity.interface';
export * from './bad-type.interface';
export * from './room.interface';
export * from './app-table.interface';
export * from './user.interface';
export * from './property-type.interface';
export * from './system-code.interface';
export * from './payment-mode.interface';
